export type SeedClient = {
  key: string;
  email: string;
  name: string;
  phone: string;
  companyName: string;
  companySize: string;
  companyIndustry: string;
  companyWebsite: string;
  companyLocation: string;
  bio: string;
};

export type SeedJob = {
  clientKey: string;
  title: string;
  description: string;
  category: string;
  skills: string[];
  budgetMin: number;
  budgetMax: number;
  budgetType: "fixed" | "hourly";
  highBadge: boolean;
  connectCost: number;
  status: "OPEN" | "HIRED" | "CLOSED";
  createdAt: string;
  hiredKey?: "maya" | "diego";
};

export const extraClients: SeedClient[] = [
  {
    key: "harbor",
    email: "elena@harborledger.example",
    name: "Elena Voss",
    phone: "+1 512 555 0174",
    companyName: "Harbor Ledger",
    companySize: "11-50",
    companyIndustry: "Finance",
    companyWebsite: "https://harborledger.example",
    companyLocation: "Austin, TX",
    bio: "Bookkeeping software for independent firms.",
  },
  {
    key: "kindling",
    email: "omar@kindling.health",
    name: "Omar Haddad",
    phone: "+1 303 555 0119",
    companyName: "Kindling Health",
    companySize: "51-200",
    companyIndustry: "Healthcare",
    companyWebsite: "https://kindling.example",
    companyLocation: "Denver, CO",
    bio: "Clinic software for independent practices.",
  },
  {
    key: "oak",
    email: "nina@oakandpine.shop",
    name: "Nina Pell",
    phone: "+1 503 555 0188",
    companyName: "Oak & Pine",
    companySize: "2-10",
    companyIndustry: "E-commerce",
    companyWebsite: "https://oakandpine.example",
    companyLocation: "Portland, OR",
    bio: "Direct-to-consumer home goods.",
  },
  {
    key: "brightline",
    email: "chris@brightline.media",
    name: "Chris Adeyemi",
    phone: "+1 347 555 0133",
    companyName: "Brightline Media",
    companySize: "11-50",
    companyIndustry: "Marketing",
    companyWebsite: "https://brightline.example",
    companyLocation: "Brooklyn, NY",
    bio: "B2B content studio.",
  },
  {
    key: "fieldnote",
    email: "sara@fieldnote.labs",
    name: "Sara Kim",
    phone: "+1 720 555 0162",
    companyName: "Fieldnote Labs",
    companySize: "11-50",
    companyIndustry: "Software & IT",
    companyWebsite: "https://fieldnote.example",
    companyLocation: "Boulder, CO",
    bio: "Field data tools for environmental teams.",
  },
  {
    key: "copperline",
    email: "marcus@copperline.logistics",
    name: "Marcus Reed",
    phone: "+1 312 555 0144",
    companyName: "Copperline Logistics",
    companySize: "201-1000",
    companyIndustry: "Operations",
    companyWebsite: "https://copperline.example",
    companyLocation: "Chicago, IL",
    bio: "Regional freight and last-mile routing.",
  },
];

export const marketplaceJobs: SeedJob[] = [
  {
    clientKey: "kindling",
    title: "Need a React engineer to finish our patient intake form (2–3 weeks)",
    description:
      "We are a 40-person clinic software company in Denver. The intake form is already in React + TypeScript. Patients can start it, but save-and-resume is broken, insurance photo upload fails on iPhone, and the Spanish copy is mixed into the English file.\n\nWhat we need done:\n- Fix save-and-resume against our existing REST API\n- Compress and retry photo uploads\n- Move copy into a simple i18n file (en / es)\n- Write a short QA checklist our nurse lead can run\n\nWe are not looking for a redesign or a rewrite. If you have shipped a similar healthcare or intake form, say so in the first paragraph and include one link. Overlap with Mountain Time is required for two standups a week.",
    category: "Web Development",
    skills: ["React", "TypeScript", "REST APIs"],
    budgetMin: 45,
    budgetMax: 75,
    budgetType: "hourly",
    highBadge: false,
    connectCost: 10,
    status: "OPEN",
    createdAt: "2026-08-28T16:40:00.000Z",
  },
  {
    clientKey: "oak",
    title: "Shopify Plus: subscription boxes keep charging the old price",
    description:
      "Oak & Pine sells seasonal home goods. We run Shopify Plus with Recharge. After we changed three bundle SKUs last month, about 180 subscribers are still billed at the 2025 price. Support is getting the tickets.\n\nNeed someone who has cleaned this up before — not a theme redesign.\n\nScope:\n- Find why Recharge is ignoring the new variant prices\n- Patch or remigrate the affected subscriptions\n- Add a one-page admin note so our ops lead can check it next season\n- Stay on Slack for 5 business days after launch\n\nPlease say how many Recharge / Shopify Plus stores you have shipped and whether you can start this week.",
    category: "Web Development",
    skills: ["Shopify", "Recharge", "Liquid"],
    budgetMin: 2800,
    budgetMax: 4200,
    budgetType: "fixed",
    highBadge: true,
    connectCost: 16,
    status: "OPEN",
    createdAt: "2026-08-26T13:15:00.000Z",
  },
  {
    clientKey: "harbor",
    title: "QuickBooks Online + Stripe: monthly reconciliation is off by $2–4k",
    description:
      "Harbor Ledger is a bookkeeping product for small CPA firms. Every month our Stripe payouts and QBO bank feed disagree by a few thousand dollars. It is usually fees, partial refunds, and disputes landing in the wrong account.\n\nWe want a contractor who has done Stripe → QBO mapping for a SaaS or marketplace, not a general bookkeeper.\n\nDeliverables:\n- Written map of payouts, fees, refunds, disputes\n- Script or Zapier/Make flow we can run on the 1st\n- 45-minute walkthrough with our staff accountant\n\nWe use Stripe Connect (destination charges). If that is not in your past work, please do not apply.",
    category: "Data",
    skills: ["Stripe", "QuickBooks", "Reconciliation"],
    budgetMin: 3500,
    budgetMax: 5500,
    budgetType: "fixed",
    highBadge: true,
    connectCost: 18,
    status: "OPEN",
    createdAt: "2026-08-24T11:05:00.000Z",
  },
  {
    clientKey: "brightline",
    title: "Ghostwriter for 6 B2B case studies (interviews already booked)",
    description:
      "Brightline is a content studio in Brooklyn. We have six customer interviews on the calendar in September (fintech and logistics brands). We need a writer who can turn a 40-minute call into a 900–1,200 word case study our clients will put on their site.\n\nYou will get a recording, a transcript, and a one-page outline. We do two rounds of edits. No AI-only first drafts — we will check.\n\nPlease send two published case studies (B2B, not lifestyle) and your turnaround time per piece. Rate can be per study or for the set.",
    category: "Writing",
    skills: ["Case studies", "B2B", "Interviews"],
    budgetMin: 2400,
    budgetMax: 3600,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "OPEN",
    createdAt: "2026-08-21T18:50:00.000Z",
  },
  {
    clientKey: "fieldnote",
    title: "Android engineer: Play Console listing + crash on Android 12 devices",
    description:
      "Fieldnote Labs makes a field-data app for watershed teams. Play Console rejected our last listing for screenshots and a missing data-safety form. Separately, Samsung A-series phones on Android 12 crash when a user opens the offline map.\n\nWe need about 30 hours over two weeks:\n- New store listing, screenshots, and data-safety answers\n- Fix the offline-map crash (Mapbox) and a short regression note\n\nKotlin codebase. We can give you a device farm login. Please mention one Play launch you have done.",
    category: "Mobile Development",
    skills: ["Kotlin", "Android", "Mapbox"],
    budgetMin: 50,
    budgetMax: 80,
    budgetType: "hourly",
    highBadge: false,
    connectCost: 10,
    status: "OPEN",
    createdAt: "2026-08-18T09:20:00.000Z",
  },
  {
    clientKey: "copperline",
    title: "Looker dashboard for on-time delivery — our ops team will not use sheets anymore",
    description:
      "Copperline moves freight in the Midwest. Dispatch still pastes CSV into Google Sheets every Monday. We have BigQuery loaded nightly. We need one Looker (or Looker Studio if you can make the case) dashboard: on-time %, dwell time, and top delay reasons by lane.\n\nYou will talk to two dispatchers and our data engineer. No executive slide deck. If the dashboard is not something a dispatcher will open at 6 a.m., it is not done.\n\n6–8 years of warehouse or logistics reporting is a plus. Include a screenshot of a similar board (blur names).",
    category: "Data",
    skills: ["BigQuery", "Looker", "SQL"],
    budgetMin: 4200,
    budgetMax: 6800,
    budgetType: "fixed",
    highBadge: true,
    connectCost: 20,
    status: "OPEN",
    createdAt: "2026-08-15T14:10:00.000Z",
  },
  {
    clientKey: "northfield",
    title: "Figma file is a mess — need a usable design system before we hire two juniors",
    description:
      "Northfield is a 22-person brand studio. Our main client file has 140 frames, no components, and three versions of the same button. We are hiring two junior designers in September and cannot onboard them into this.\n\nNeed a contractor to:\n- Audit the file and throw out unused frames (we will approve the cut list)\n- Build a small library: type, color, buttons, inputs, cards\n- Write a one-page “how we use this file” note\n\nThis is not a rebrand. You will work inside our existing green/cream palette. Please show a before/after from a file you cleaned.",
    category: "Design",
    skills: ["Figma", "Design systems", "UI kit"],
    budgetMin: 2200,
    budgetMax: 3400,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "OPEN",
    createdAt: "2026-08-12T17:30:00.000Z",
  },
  {
    clientKey: "lumenops",
    title: "Intercom: we need a first-response playbook and 25 macros by Friday week after next",
    description:
      "LumenOps support is four people and a pile of saved replies nobody trusts. Average first response is 11 hours. We want a contractor who has set up Intercom for a B2B SaaS team, not a general VA.\n\nWork:\n- Listen to 15 recent tickets (we will export)\n- Write a first-response standard (when to escalate, when to refund, when to book CS)\n- Build 25 macros and a simple teammate view\n- 90-minute training on a recorded Zoom\n\nEnglish native or equivalent. Overlap with US Pacific 10–1 a few days.",
    category: "Customer Support",
    skills: ["Intercom", "Macros", "Support ops"],
    budgetMin: 1600,
    budgetMax: 2300,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "OPEN",
    createdAt: "2026-08-09T20:05:00.000Z",
  },
  {
    clientKey: "oak",
    title: "Need a photographer who can shoot 40 SKUs in our Portland studio",
    description:
      "We have a daylight studio in SE Portland for two days in mid-September. 40 SKUs: ceramics, linen, and small furniture. We need consistent web images (4:5) plus 8 lifestyle frames for the homepage.\n\nYou bring lights if we need them; we have a foam sweep and a stylist for one of the days. Deliver edited JPEGs + RAWs within 5 business days.\n\nLocal to Portland strongly preferred. Please send a product-photo set, not portraits.",
    category: "Design",
    skills: ["Product photography", "Retouching", "E-commerce"],
    budgetMin: 1800,
    budgetMax: 2600,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "OPEN",
    createdAt: "2026-08-06T15:45:00.000Z",
  },
  {
    clientKey: "harbor",
    title: "Part-time bookkeeper who is comfortable in Stripe and Gusto (ongoing)",
    description:
      "We need 8–10 hours a week for the rest of the year: categorize Harbor Ledger’s own books, chase two contractor invoices, and keep Gusto payroll in QBO. This is not client work — it is our internal books.\n\nMust have used Stripe dashboard and Gusto before. CPA not required. Weekly Slack check-in, no video unless something is off.\n\nStart with a 30-day trial at the hourly rate, then we talk about a longer retainer.",
    category: "Data",
    skills: ["Bookkeeping", "Gusto", "QuickBooks"],
    budgetMin: 35,
    budgetMax: 55,
    budgetType: "hourly",
    highBadge: false,
    connectCost: 10,
    status: "OPEN",
    createdAt: "2026-08-03T12:00:00.000Z",
  },

  {
    clientKey: "northfield",
    title: "Squarespace 7.1 site for a ceramicist — launched March 2019",
    description:
      "Built a 12-page Squarespace site with a simple shop, mailing list, and a password page for wholesale. Client supplied photos. We hired on Wova and closed after launch plus two weeks of tweaks.",
    category: "Web Development",
    skills: ["Squarespace", "CSS", "E-commerce"],
    budgetMin: 1400,
    budgetMax: 1900,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "HIRED",
    createdAt: "2019-02-11T16:20:00.000Z",
    hiredKey: "maya",
  },
  {
    clientKey: "brightline",
    title: "Ghostwritten LinkedIn series for a Series A founder (12 weeks)",
    description:
      "Weekly posts and two long articles for a payments founder. Voice guide and interview notes were provided. Contract ran Feb–May 2019.",
    category: "Writing",
    skills: ["Ghostwriting", "LinkedIn", "Thought leadership"],
    budgetMin: 4800,
    budgetMax: 4800,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "HIRED",
    createdAt: "2019-02-04T14:00:00.000Z",
    hiredKey: "maya",
  },
  {
    clientKey: "copperline",
    title: "Excel model: lane rates vs. diesel for 2019 budget",
    description:
      "Dispatcher-facing workbook with diesel surcharge scenarios. Replaced a fragile VLOOKUP file. Delivered before their March board packet.",
    category: "Data",
    skills: ["Excel", "Modeling", "Logistics"],
    budgetMin: 2200,
    budgetMax: 2800,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "HIRED",
    createdAt: "2019-11-18T10:30:00.000Z",
    hiredKey: "diego",
  },
  {
    clientKey: "kindling",
    title: "HIPAA review of our patient-email templates",
    description:
      "Lawyer-adjacent contractor reviewed 22 email templates and flagged PHI in three of them. We closed after the memo; engineering implemented the cuts.",
    category: "Writing",
    skills: ["HIPAA", "Healthcare", "Editing"],
    budgetMin: 1600,
    budgetMax: 2100,
    budgetType: "fixed",
    highBadge: true,
    connectCost: 15,
    status: "CLOSED",
    createdAt: "2020-05-06T13:40:00.000Z",
  },
  {
    clientKey: "fieldnote",
    title: "iOS 14: background location permission rewrite",
    description:
      "Apple rejected the build. Contractor rewrote the permission string, added a pre-prompt screen, and got us through review in nine days.",
    category: "Mobile Development",
    skills: ["Swift", "iOS", "App Store"],
    budgetMin: 3000,
    budgetMax: 3800,
    budgetType: "fixed",
    highBadge: true,
    connectCost: 16,
    status: "HIRED",
    createdAt: "2020-09-14T17:05:00.000Z",
    hiredKey: "diego",
  },
  {
    clientKey: "oak",
    title: "Klaviyo flows after we left Mailchimp (holiday 2020)",
    description:
      "Welcome, abandon cart, and post-purchase for a 28k list. Revenue attributed in Klaviyo for Nov–Dec. Hired a contractor who had done two similar migrations.",
    category: "Marketing",
    skills: ["Klaviyo", "Email", "E-commerce"],
    budgetMin: 1900,
    budgetMax: 2500,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "HIRED",
    createdAt: "2020-10-02T15:22:00.000Z",
    hiredKey: "maya",
  },
  {
    clientKey: "lumenops",
    title: "SOC 2 evidence folder — policies we could actually follow",
    description:
      "Wrote access-control, incident, and vendor policies in plain English and sat with engineering for two working sessions. Auditor accepted the pack in 2021.",
    category: "Writing",
    skills: ["SOC 2", "Policies", "Security"],
    budgetMin: 5200,
    budgetMax: 6800,
    budgetType: "fixed",
    highBadge: true,
    connectCost: 18,
    status: "HIRED",
    createdAt: "2021-03-29T12:10:00.000Z",
    hiredKey: "maya",
  },
  {
    clientKey: "harbor",
    title: "Plaid + QBO: bank connections dropping overnight",
    description:
      "Customers were reconnecting every few days. Contractor traced token refresh, added retry, and a support runbook. Closed after 30 days of clean logs.",
    category: "Web Development",
    skills: ["Plaid", "Node.js", "QuickBooks"],
    budgetMin: 6000,
    budgetMax: 8500,
    budgetType: "fixed",
    highBadge: true,
    connectCost: 20,
    status: "HIRED",
    createdAt: "2021-07-19T09:50:00.000Z",
    hiredKey: "diego",
  },
  {
    clientKey: "brightline",
    title: "Webflow marketing site — we outgrew the Webflow trial",
    description:
      "Five pages, CMS for work, HubSpot form. Contractor handed off Editor training. Site stayed on Webflow until 2023.",
    category: "Web Development",
    skills: ["Webflow", "CMS", "HubSpot"],
    budgetMin: 3200,
    budgetMax: 4000,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "HIRED",
    createdAt: "2021-11-08T18:15:00.000Z",
    hiredKey: "maya",
  },
  {
    clientKey: "copperline",
    title: "Driver Android app: barcode scan was 4 seconds too slow",
    description:
      "Warehouse leads were skipping scans. Contractor swapped the camera library, added a torch toggle, and cut scan time. Rolled out to 90 drivers.",
    category: "Mobile Development",
    skills: ["Android", "Kotlin", "Camera"],
    budgetMin: 40,
    budgetMax: 65,
    budgetType: "hourly",
    highBadge: false,
    connectCost: 10,
    status: "HIRED",
    createdAt: "2022-04-12T11:25:00.000Z",
    hiredKey: "diego",
  },
  {
    clientKey: "kindling",
    title: "Figma prototype for a refill-request flow (clinician + patient)",
    description:
      "Two-week prototype, tested with four clinicians. We did not hire for build — design only. File is still the source of truth.",
    category: "Design",
    skills: ["Figma", "UX", "Healthcare"],
    budgetMin: 2700,
    budgetMax: 3300,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "HIRED",
    createdAt: "2022-08-30T16:40:00.000Z",
    hiredKey: "maya",
  },
  {
    clientKey: "fieldnote",
    title: "Python: nightly NOAA weather pull into Postgres",
    description:
      "Cron job, retries, and a Slack ping if a station is missing. Ran through two winters without a page.",
    category: "Data",
    skills: ["Python", "Postgres", "ETL"],
    budgetMin: 2400,
    budgetMax: 3100,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "HIRED",
    createdAt: "2023-01-17T08:55:00.000Z",
    hiredKey: "diego",
  },
  {
    clientKey: "oak",
    title: "Meta ads: we paused after iOS 14 and never rebuilt audiences",
    description:
      "Contractor rebuilt three catalog campaigns and a lookalike from purchasers only. 90-day engagement, then we took it in-house.",
    category: "Marketing",
    skills: ["Meta Ads", "Catalog", "Analytics"],
    budgetMin: 1500,
    budgetMax: 2200,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "CLOSED",
    createdAt: "2023-06-05T19:10:00.000Z",
  },
  {
    clientKey: "lumenops",
    title: "Next.js 13 app router migration — marketing only, not the app",
    description:
      "Moved 18 marketing routes off pages/. Kept the product on the old router. Contractor left a migration note we still use.",
    category: "Web Development",
    skills: ["Next.js", "App Router", "SEO"],
    budgetMin: 4800,
    budgetMax: 6400,
    budgetType: "fixed",
    highBadge: true,
    connectCost: 17,
    status: "HIRED",
    createdAt: "2023-10-23T13:00:00.000Z",
    hiredKey: "diego",
  },
  {
    clientKey: "harbor",
    title: "Customer interviews: why firms churn after month 4",
    description:
      "Eight interviews, a 7-page memo, and a clip reel. We used it to change onboarding, then closed the contract.",
    category: "Product",
    skills: ["Research", "Interviews", "SaaS"],
    budgetMin: 2100,
    budgetMax: 2600,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "HIRED",
    createdAt: "2024-02-14T15:35:00.000Z",
    hiredKey: "maya",
  },
  {
    clientKey: "brightline",
    title: "HubSpot pipeline cleanup after two years of junk stages",
    description:
      "Collapsed 14 stages to 6, rebuilt reports, and trained three AEs. They kept the contractor one extra week for office hours.",
    category: "Marketing",
    skills: ["HubSpot", "CRM", "Revenue ops"],
    budgetMin: 2800,
    budgetMax: 3600,
    budgetType: "fixed",
    highBadge: false,
    connectCost: 10,
    status: "HIRED",
    createdAt: "2024-07-09T10:05:00.000Z",
    hiredKey: "maya",
  },
  {
    clientKey: "copperline",
    title: "Snowflake: stop paying for queries nobody runs",
    description:
      "Warehouse review, clustered two large tables, killed unused dashboards. Monthly compute dropped enough that finance asked for a write-up.",
    category: "Data",
    skills: ["Snowflake", "SQL", "Cost"],
    budgetMin: 5500,
    budgetMax: 7200,
    budgetType: "fixed",
    highBadge: true,
    connectCost: 19,
    status: "HIRED",
    createdAt: "2024-12-02T14:48:00.000Z",
    hiredKey: "diego",
  },
  {
    clientKey: "kindling",
    title: "We tried to hire for a full EHR rewrite — cancelled after scoping",
    description:
      "Posted a large build, got proposals, then our board paused the project. Job closed with no hire. Left up so talent can see we still pay for smaller scoped work.",
    category: "Web Development",
    skills: ["EHR", "React", "HL7"],
    budgetMin: 40000,
    budgetMax: 80000,
    budgetType: "fixed",
    highBadge: true,
    connectCost: 20,
    status: "CLOSED",
    createdAt: "2025-04-16T16:12:00.000Z",
  },
  {
    clientKey: "fieldnote",
    title: "Figma → Flutter handoff for our new sample-log screen",
    description:
      "Designer + Flutter pair. Shipped the sample-log screen to TestFlight in five weeks. Contract ended at 1.0.",
    category: "Mobile Development",
    skills: ["Flutter", "Figma", "Dart"],
    budgetMin: 7200,
    budgetMax: 9000,
    budgetType: "fixed",
    highBadge: true,
    connectCost: 18,
    status: "HIRED",
    createdAt: "2025-09-08T12:28:00.000Z",
    hiredKey: "diego",
  },
];
